FROM node:20.19.4-alpine3.21

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the project dependencies
RUN npm install

# Copy the entire project directory to the working directory in the container
COPY . .

# Expose the port that the frontend application will run on
EXPOSE 5173

# Start the frontend application
CMD ["npm", "run", "dev", "--", "--host"]